language: node_js
node_js:
  - 'node'
cache:
  yarn: true
before_deploy: yarn global add now
deploy:
  - provider: script
    script: bash scripts/deploy_review_app.sh
    skip_cleanup: true
    on:
      all_branches: true
      tags: false
      condition: $TRAVIS_BRANCH != "master"
  - provider: script
    script: bash scripts/deploy_staging_app.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy_production_app.sh
    skip_cleanup: true
    on:
      tags: true
 - provider: script
    script: bash scripts/tag_and_push.sh
    skip_cleanup: true
    on:
      master: true
      condition: -z $(git tag --points-at $TRAVIS_COMMIT)